modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/thinkverse/extended-slabs/issues"

[[mods]]
    modId="extendedslabs"
    version="${file.jarVersion}"
    displayName="Extended Slabs"
    displayURL="https://thinkverse.dev"
    updateJSONURL="https://thinkverse.dev/extended-slabs/update"
    logoFile="examplemod.png"
    credits="Clownvin, HarryTechRevs, SilentChaos512 & Champion Ash5357"
    authors="Thinkverse"
    description='''
    This mod adds vertical slabs and more to Minecraft.
    '''

[[dependencies.versecraft]]
    modId="forge"
    mandatory=true
    versionRange="[26,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.versecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.2]"
    ordering="NONE"
    side="BOTH"